/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Administrador;
import Clases.Almacenero;
import Clases.AtencionCliente;
//import Clases.Cliente;
import Clases.LectorDeTarjetas;
import dao.component.BDRelacionalClienteDAO;
import dao.component.BDRelacionalTarjetaDAO;
import dao.to.ClienteTO;
import dao.to.TarjetaTO;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Orlando
 */
public class Login extends javax.swing.JFrame {
//7750670244954
    /**
     * Creates new form Login
     */
    LectorDeTarjetas lector=new LectorDeTarjetas();
    Administrador admin=new Administrador("Julian Perez",74757889,78945 , "julian@hotmail.com", "calle los claveles mz d lt 21",2000.00,"AD100","123");
    Almacenero almac=new Almacenero("Danni Rabanal",74757889,78945 , "danni@hotmail.com", "calle los claveles mz d lt 21",2000.00,"AL100","123");
    AtencionCliente atcli=new AtencionCliente("Felicita Ramones",88546984,78452,"felicita@hotmail.com","calle amapolas mz d lt 4",3000.00,"AC100","123");
    ClienteTO clien=new ClienteTO();
    
    public Login() {
        initComponents();
        
       
       //userName.setText( lector.getCodTarjeta());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        botonAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 198, 75, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 224, 75, -1));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 198, 99, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 225, 99, -1));

        botonAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 291, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BIENVENIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 77, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 74, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carrito.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 27, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MINI MARKET \"CAMARENA\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 27, -1, 41));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userImg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 198, 56, 56));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        TarjetaTO tj;
        BDRelacionalClienteDAO cl =new BDRelacionalClienteDAO();
            String codigoTarjeta = userName.getText();
            BDRelacionalTarjetaDAO dao = new BDRelacionalTarjetaDAO();
            tj = dao.obtenerTarjeta(codigoTarjeta);
       //boolean resp=lector.validaTarjeta(userName.getText());
        
        if(admin.getID().equals(userName.getText())&&admin.getPassword().equals(password.getText())){
            UserAdmin usAdmin = new UserAdmin(admin);//instancia de jframe 
            usAdmin.setVisible(true);  //LLama a jfram 
            dispose(); //Cierra la ventana anterior
        }else if(almac.getID().equals(userName.getText())&&almac.getPassword().equals(password.getText())){
            UserAlmacenero usAlmac = new UserAlmacenero(almac);//instancia de jframe 
            usAlmac.setVisible(true);  //LLama a jfram 
            dispose(); //Cierra la ventana anterior
        }else if(atcli.getID().equals(userName.getText())&&atcli.getPassword().equals(password.getText())){
            UserAtenCliente usAtcli = new UserAtenCliente(atcli);//instancia de jframe 
            usAtcli.setVisible(true);  //LLama a jfram 
            dispose(); //Cierra la ventana anterior
        }else if(tj.getCodTarjeta().equals(codigoTarjeta)){
            clien=cl.obtenerCliente(tj.getNroCuenta());
            UserCliente usCli = new UserCliente(clien);//instancia de jframe 
            usCli.setVisible(true);  //LLama a jfram 
            dispose(); //Cierra la ventana anterior
        }else         
            JOptionPane.showMessageDialog(null,"Usuario o contraseña invalido","Error",JOptionPane.ERROR_MESSAGE);        
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
