/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import dao.component.BDRelacionalPromocionDAO;
import dao.to.PromocionTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Orlando
 */
public class MantenerPromocion extends javax.swing.JFrame {

    /**
     * Creates new form promocion
     */
    List<PromocionTO> listaPro;

    public MantenerPromocion() {
        initComponents();
        MostrarTodosPromociones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAniadir = new javax.swing.JButton();
        txtproducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carrito.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MINI MARKET \"CAMARENA\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, -1, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("PROMOCION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 68, -1, 23));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AnuncionPromo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 56, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Codigo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 124, 54, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 163, -1, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Costo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 206, 54, 24));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 124, 100, 31));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 165, 100, 29));

        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 208, 100, 24));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descripción:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 126, -1, 29));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cantidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 163, 77, 29));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 128, 100, 29));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 164, 100, 31));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 272, -1, 120));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 225, 93, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 190, 93, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 155, -1, -1));

        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 120, 93, -1));

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 206, 100, 27));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Producto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 210, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here
        try {
            PromocionTO promocion = new PromocionTO();
            promocion.setCodigo(this.txtCodigo.getText());
            promocion.setCodProducto(this.txtproducto.getText());
            promocion.setNombre(this.txtNombre.getText());
            promocion.setDescripcion(this.txtDescripcion.getText());
            promocion.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
            promocion.setCosto(Double.parseDouble(this.txtCosto.getText()));

            BDRelacionalPromocionDAO dao = new BDRelacionalPromocionDAO();
            dao.insertarPromocion(promocion);
            MostrarTodosPromociones();
            JOptionPane.showMessageDialog(null, "Producto Añadido");
            //JOptionPane.showMessageDialog(null, "Código de producto no debe estar vacío", "PROMOCIÓN NO AÑADIDA", JOptionPane.WARNING_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos");
        }
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here
        String codigo = JOptionPane.showInputDialog("Ingrese el ID del producto que desea eliminar");
        BDRelacionalPromocionDAO dao = new BDRelacionalPromocionDAO();
        int n = Buscar(codigo);

        if (n == 1) {
            int r = JOptionPane.showConfirmDialog(this, "Esra seguro de eliminar el produto?", "Responder", 0);
            if (r == 0) {
                dao.eliminarPromocion(codigo);
                MostrarTodosPromociones();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            PromocionTO promocion2 = new PromocionTO();
            promocion2.setCodigo(this.txtCodigo.getText());
            promocion2.setCodProducto(this.txtproducto.getText());
            promocion2.setNombre(this.txtNombre.getText());
            promocion2.setDescripcion(this.txtDescripcion.getText());
            promocion2.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
            promocion2.setCosto(Double.parseDouble(this.txtCosto.getText()));
            BDRelacionalPromocionDAO dao = new BDRelacionalPromocionDAO();
            dao.actualizarPromocion(promocion2);
            MostrarTodosPromociones();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog("Ingres el ID de la promocion que desea buscar0");

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int seleccion = jTable1.rowAtPoint(evt.getPoint());
        txtCodigo.setText(String.valueOf(jTable1.getValueAt(seleccion, 0)));
        txtproducto.setText(String.valueOf(jTable1.getValueAt(seleccion, 1)));
        txtNombre.setText(String.valueOf(jTable1.getValueAt(seleccion, 2)));
        txtDescripcion.setText(String.valueOf(jTable1.getValueAt(seleccion, 3)));
        txtCosto.setText(String.valueOf(jTable1.getValueAt(seleccion, 4)));
        txtCantidad.setText(String.valueOf(jTable1.getValueAt(seleccion, 5)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed
    private void MostrarTodosPromociones() {
        BDRelacionalPromocionDAO dao = new BDRelacionalPromocionDAO();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CODIGO");
        //model.addColumn("COD_PROD");
        model.addColumn("NOMBRE");
        model.addColumn("DESCRIPCION");
        //model.addColumn("COSTO S/.");
        model.addColumn("CANTIDAD");

        jTable1.setModel(model);
        listaPro = dao.listarPromocion();

        for (int i = 0; i < listaPro.size(); i++) {
            Object[] row = {listaPro.get(i).getCodigo(),// listaPro.get(i).getCodProducto(),
                listaPro.get(i).getNombre(), listaPro.get(i).getDescripcion(),// listaPro.get(i).getCosto(), 
                listaPro.get(i).getCantidad()};
            model.addRow(row);
        }
    }

    private int Buscar(String codigo) {
        BDRelacionalPromocionDAO dao = new BDRelacionalPromocionDAO();
        listaPro = dao.listarPromocionCodigo();
        for (int i = 0; i < listaPro.size(); i++) {
            if (listaPro.get(i).getCodigo().equals(codigo)) {
                return 1;
            }
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables

}
