/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import dao.component.BDRelacionalClienteDAO;
import dao.to.ClienteTO;
import dao.to.TarjetaTO;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Orlando
 */
public class MantenerCliente extends javax.swing.JFrame {

    /**
     * Creates new form MantenerCliente
     */
    List<ClienteTO> listaCli;

    public MantenerCliente() {
        initComponents();
        MostrarTodosClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtNumCuenta = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        btnAniadir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablacli = new javax.swing.JTable();
        jButtonVolverLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MINI MARKET \"CAMARENA\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 56, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carrito.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userImg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 152, 69, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 205, 93, -1));
        getContentPane().add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 100, 100, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 170, 93, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 126, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("N° Cuenta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 100, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 126, 69, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 135, -1, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 152, 100, -1));

        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 100, 93, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("DNI:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 178, 69, -1));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 178, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Edad:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 103, 20));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 102, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("E-mail:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 185, 69, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 185, 100, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 128, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Distrito:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 128, 69, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Telefono:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 159, 69, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 159, 100, -1));

        tablacli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacliMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tablacli);

        jScrollPane5.setViewportView(jScrollPane6);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 539, 165));

        jButtonVolverLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa.png"))); // NOI18N
        jButtonVolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 411, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here:

        try {
            ClienteTO cli = new ClienteTO();
            cli.setNroCuenta(this.txtNumCuenta.getText());
            cli.setNombre(this.txtNombre.getText());
            cli.setApellido(this.txtApellido.getText());
            cli.setDNI(Integer.parseInt(this.txtDNI.getText()));
            cli.setDireccion(this.txtDireccion.getText());
            cli.setEdad(Integer.parseInt(this.txtEdad.getText()));
            cli.setTelefono(Integer.parseInt(this.txtTelefono.getText()));
            cli.setEmail(this.txtEmail.getText());

            BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
            dao.insertarCliente(cli);
            MostrarTodosClientes();
            //Insertar tarjeta
            TarjetaTO tarjeta=new TarjetaTO();
            String codTarjeta= "TJ"+ txtNumCuenta.getText().substring(1,3);
                    System.out.println(codTarjeta);
            Calendar c=Calendar.getInstance();
            int dia=c.get(Calendar.DATE);
            int mes=c.get(Calendar.MONTH);
            int annio = c.get(Calendar.YEAR);
            
            Date fechacad;
            fechacad=new Date(annio-1900+1,mes,dia);
            tarjeta.setCodTarjeta(codTarjeta);
            tarjeta.setNroCuenta(this.txtNumCuenta.getText());
            tarjeta.setFechaVencimiento(fechacad);
            tarjeta.setSaldo(0.0);
            
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos");
        }
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog("Ingrese el ID del Cliente que desea eliminar");
        BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
        int n = Buscar(codigo);
        if (n == 1) {
            int r = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar a éste cliente ?",
                    "Reponder", 0);
            if (r == 0)// si
            {
                dao.eliminarCliente(codigo);
                MostrarTodosClientes();
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            ClienteTO cli2 = new ClienteTO();
            cli2.setNroCuenta(this.txtNumCuenta.getText());
            cli2.setNombre(this.txtNombre.getText());
            cli2.setApellido(this.txtApellido.getText());
            cli2.setDNI(Integer.parseInt(this.txtDNI.getText()));
            cli2.setDireccion(this.txtDireccion.getText());
            cli2.setEdad(Integer.parseInt(this.txtEdad.getText()));
            cli2.setTelefono(Integer.parseInt(this.txtTelefono.getText()));
            cli2.setEmail(this.txtEmail.getText());

            BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
            dao.actualizarCliente(cli2);
            MostrarTodosClientes();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog("Ingrese el ID del Cliente que desea buscar");
        BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
        int n = Buscar(codigo);
        if (n == 1) {
            
                
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablacliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacliMouseClicked
        // TODO add your handling code here:
        int seleccion= tablacli.rowAtPoint(evt.getPoint());
        txtNumCuenta.setText(String.valueOf(tablacli.getValueAt(seleccion, 0)));
        txtNombre.setText(String.valueOf(tablacli.getValueAt(seleccion, 1)));
        txtApellido.setText(String.valueOf(tablacli.getValueAt(seleccion, 2)));
        txtDNI.setText(String.valueOf(tablacli.getValueAt(seleccion, 3)));
        txtDireccion.setText(String.valueOf(tablacli.getValueAt(seleccion, 7)));
        txtEdad.setText(String.valueOf(tablacli.getValueAt(seleccion, 5)));
        txtEmail.setText(String.valueOf(tablacli.getValueAt(seleccion, 6)));
        txtTelefono.setText(String.valueOf(tablacli.getValueAt(seleccion, 4)));
    }//GEN-LAST:event_tablacliMouseClicked

    private void jButtonVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverLoginActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverLoginActionPerformed
 

    public int Buscar(String nroCuenta) {
        BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
        listaCli = dao.listarClientesCodigo();
        for (int i = 0; i < listaCli.size(); i++) {
            if (listaCli.get(i).getNroCuenta().equals(nroCuenta)) {
                return 1;
            }
        }
        return -1;
    }

    public void MostrarTodosClientes() {

        BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
        DefaultTableModel modelo1 = new DefaultTableModel();
        //DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("APELLIDOS");
        modelo1.addColumn("DNI");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EDAD");
        modelo1.addColumn("E-MAIL");
        modelo1.addColumn("DISTRITO");

        tablacli.setModel(modelo1);
        listaCli = dao.listarClientes();

        for (int i = 0; i < listaCli.size(); i++) {
            Object[] row = {listaCli.get(i).getNroCuenta(), listaCli.get(i).getNombre(), listaCli.get(i).getApellido(),
                listaCli.get(i).getDNI(), listaCli.get(i).getTelefono(), listaCli.get(i).getEdad(),
                listaCli.get(i).getEmail(), listaCli.get(i).getDireccion()};
            modelo1.addRow(row);
        }
        

    }
//     public void MostrarUnClientes(String codigo) {
//
//        BDRelacionalClienteDAO dao = new BDRelacionalClienteDAO();
//        DefaultTableModel modelo1 = new DefaultTableModel();
//        //DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
//        modelo1.addColumn("ID");
//        modelo1.addColumn("NOMBRE");
//        modelo1.addColumn("APELLIDOS");
//        modelo1.addColumn("DNI");
//        modelo1.addColumn("TELEFONO");
//        modelo1.addColumn("EDAD");
//        modelo1.addColumn("E-MAIL");
//        modelo1.addColumn("DISTRITO");
//
//        tablacli.setModel(modelo1);
//        listaCli = dao.listarClientes();
//
//        if(codigo.equals(dao)) {
//            Object[] row = {listaCli.get(i).getNroCuenta(), listaCli.get(i).getNombre(), listaCli.get(i).getApellido(),
//                listaCli.get(i).getDNI(), listaCli.get(i).getTelefono(), listaCli.get(i).getEdad(),
//                listaCli.get(i).getEmail(), listaCli.get(i).getDireccion()};
//            modelo1.addRow(row);
//        }
//     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonVolverLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablacli;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
