/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import dao.component.BDRelacionalRecargaDAO;
import dao.component.BDRelacionalTarjetaDAO;
import dao.to.RecargaTO;
import dao.to.TarjetaTO;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Orlando
 */
public class Recarga extends javax.swing.JFrame {

    /**
     * Creates new form Recarga
     */
    public Recarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        labelSaldoActual = new javax.swing.JLabel();
        txtCodRecarga = new javax.swing.JTextField();
        labeltotal = new javax.swing.JLabel();
        jButtonVolverLogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MINI MARKET \"CAMARENA\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, -1, 41));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carrito.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cardClient.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 58, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("RECARGA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 70, -1, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Actual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 162, 117, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("N° Tarjeta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 125, 117, 29));
        getContentPane().add(txtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 127, 100, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 239, 117, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Monto de Recarga:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 202, -1, 29));
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 204, 100, 29));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 289, 96, 34));
        getContentPane().add(labelSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 162, 100, 34));

        txtCodRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRecargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 99, 125, -1));
        getContentPane().add(labeltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 100, 21));

        jButtonVolverLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa.png"))); // NOI18N
        jButtonVolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 321, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            TarjetaTO tj;
            String codigoTarjeta = txtNumTarjeta.getText();
            BDRelacionalTarjetaDAO dao = new BDRelacionalTarjetaDAO();
            tj = dao.obtenerTarjeta(codigoTarjeta);

            if (tj.getCodTarjeta().equals(codigoTarjeta)) {
                RecargaTO re = new RecargaTO();
                re.setCodigo(txtCodRecarga.getText());
                re.setCodigoTarjeta(codigoTarjeta);
                re.setMonto(Double.parseDouble(txtMonto.getText()));
                BDRelacionalRecargaDAO dao1 = new BDRelacionalRecargaDAO();
                dao1.insertarRecarga(re);
                Double saldoactual = tj.getSaldo() + Double.parseDouble(txtMonto.getText());
                dao.actualizarTarjeta(saldoactual, tj.getCodTarjeta());
            } else {
                JOptionPane.showMessageDialog(null, "La tarjeta no existe", "Validación de datos", JOptionPane.WARNING_MESSAGE);

            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCodRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRecargaActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
      
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButtonVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverLoginActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonVolverLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelSaldoActual;
    private javax.swing.JLabel labeltotal;
    private javax.swing.JTextField txtCodRecarga;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumTarjeta;
    // End of variables declaration//GEN-END:variables
}
